project:
  type: website

website:
  title: "Dr. Dominique Lamonica"
  navbar:
    left:
      - href: index.qmd
        text: Current work
      - href: cv.qmd
        text: Education & Jobs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
